(()=>{"use strict";
const P=window.ALUMINUM_PRICE_DATA;const $=id=>document.getElementById(id);let items=[];
const e={w:$("widthInput"),h:$("heightInput"),q:$("qtyInput"),minus:$("minusBtn"),plus:$("plusBtn"),add:$("addWindow"),tbody:document.querySelector("#windowTable tbody"),empty:$("emptyText"),cur:$("currentAmount"),totC:$("totalCount"),totA:$("totalAmount"),totO:$("totalOrderQty")};
const comma=n=>Math.round(Number(n)||0).toLocaleString('ko-KR');const won=n=>comma(n)+' 원';const orderQty=n=>Math.ceil((Number(n)||0)/(P.unitCafe||1000));
function exact(mm){const n=Number(mm);if(!Number.isInteger(n)||n<1||n>(P.maxSizeCm||300)*10)return null;return n}
function optCm(mm){return Math.ceil(mm/10)}
function calc(w,h){w=exact(w);h=exact(h);if(w===null||h===null)return{valid:false,amount:0};const calcW=Math.max(900,w),calcH=Math.max(900,h),smartMax=(P.smartStoreMaxSizeCm||220)*10,cells=Math.ceil((calcW*calcH)/90000),baseCells=P.baseCells||4,extraCells=Math.max(0,cells-baseCells),isStore=calcW<=smartMax&&calcH<=smartMax;let unit=0,mode='';if(isStore){const ow=optCm(calcW),oh=optCm(calcH),we=P.widthOptions?.[String(ow)]||0,he=P.heightOptions?.[String(oh)]||0;unit=(P.basePrice||14000)+we+he;mode='스마트스토어'}else{const bw=Math.min(calcW,smartMax),bh=Math.min(calcH,smartMax),bow=optCm(bw),boh=optCm(bh),boundary=(P.basePrice||14000)+(P.widthOptions?.[String(bow)]||0)+(P.heightOptions?.[String(boh)]||0),boundaryCells=Math.ceil((bw*bh)/90000),added=Math.max(0,cells-boundaryCells),large=boundary+added*(P.consumerUnitPrice||5500),standard=(P.basePrice||14000)+extraCells*(P.standardConsumerUnitPrice||4500);unit=Math.max(standard,large);mode='대형맞춤'}return{valid:true,w,h,calcW,calcH,unit,mode}}
function current(){const r=calc(e.w.value,e.h.value),q=Math.max(1,Number(e.q.value||1));e.cur.textContent=r.valid?won(r.unit*q):'0 원'}
function addItem(){const q=Math.max(1,Number(e.q.value||1)),r=calc(e.w.value,e.h.value);if(!e.w.value||!e.h.value)return alert('가로와 세로를 입력해주세요.');if(!r.valid)return alert('가로와 세로를 1~3000mm 범위의 정수로 입력해주세요.');for(let i=0;i<q;i++)items.push({...r});e.w.value='';e.h.value='';e.q.value=1;render()}
function render(){current();e.tbody.innerHTML='';let total=0;items.forEach((it,i)=>{total+=it.unit;const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${it.w}</td><td>${it.h}</td><td>${it.calcW}×${it.calcH}</td><td>${won(it.unit)}</td><td><button type="button" class="del-btn">삭제</button></td>`;tr.querySelector('button').onclick=()=>{items.splice(i,1);render()};e.tbody.appendChild(tr)});e.empty.style.display=items.length?'none':'flex';e.totC.textContent=items.length+' 개';e.totA.textContent=won(total);e.totO.textContent=comma(orderQty(total))+' 개'}
['input','change'].forEach(ev=>{e.w.addEventListener(ev,render);e.h.addEventListener(ev,render);e.q.addEventListener(ev,render)});e.minus.onclick=()=>{e.q.value=Math.max(1,Number(e.q.value||1)-1);render()};e.plus.onclick=()=>{e.q.value=Number(e.q.value||1)+1;render()};e.add.onclick=addItem;render();
})();